default: &default
  adapter: mysql2
  host: localhost
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'password' %>

development:
  adapter: sqlite3
  database: development.db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  host: db
  database: production_db
