db:
  development:
    adapter: mysql2
    host: localhost
    username: root
    password: password
    database: development_db

  test:
    adapter: mysql2
    host: localhost
    username: root
    password: password
    database: test_db
