# A sample Gemfile
source "https://rubygems.org"

# gem 
gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'activesupport'
gem 'sinatra-activerecord'
gem 'mysql2'
gem 'foreigner'
gem 'erubis'
gem 'grape'