source "https://rubygems.org"

gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activerecord'
gem 'activesupport'

gem 'actionpack'
gem 'sinatra-activerecord'
gem 'foreigner'
gem 'erubis'
gem 'grape'
gem 'unicorn'
gem 'holiday_jp'
gem 'database_cleaner'
gem "foreman"

group :production do
  gem 'mysql2'
end

group :development, :test do
  # for test
  gem 'rspec'
  gem 'guard-rspec'
  gem 'capybara'
  gem 'cucumber'
  gem 'poltergeist'

  gem "sqlite3"
  gem "sinatra-reloader"
end
