# A sample Gemfile
source "https://rubygems.org"

# gem
gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'activerecord'
gem 'activesupport'
gem 'actionpack'
gem 'sinatra-activerecord'
gem 'mysql2'
gem 'foreigner'
gem 'erubis'
gem 'grape'
gem 'rspec'
gem 'guard-rspec'
gem 'unicorn'
gem 'holiday_jp'
gem 'capybara'
gem 'cucumber'
gem 'poltergeist'
gem 'database_cleaner'

group :development, :test do
  gem "sqlite3"
  gem "sinatra-reloader"
  gem "foreman"
end
